name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Set all tokens
      run: >-
        npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPMCORP_TOKEN }}
        
    - name: Build
      run: npm ci
    
    - name: Lint
      run: npm run lint

    - name: Test
      run: npm test